
insert into monster (MonsterName,MonsterIcon,Carves) values ('Dummie','Question_Mark.png','0'),('Acidic Glavenus','Acidic_Glavenus.png','3'),
('Alatreon','Alatreon.png','6'),
('Anciente Leshen','Ancient_Leshen.png','5'),
('Anjanath','Anjanath.png','3'),
('Azure Rathalos','Azure_Rathalos.png','3'),
('Banbaro','Banbaro.png','3'),
('Barioth','Barioth.png','3'),
('Barroth','Barroth.png','3'),
('Bazelgeus','Bazelgeus.png','4'),
('Behemoth','Behemoth.png','6'),
('Beotodus','Beotodus.png','3'),
('Black_Diablos','Black_Diablos.png','3'),
('Blackveil Vaal Hazak','Blackveil_Vaal_Hazak.png','4'),
('Brachydios','Brachydios.png','3'),
('Brute Tigrex','Brute_Tigrex.png','3'),
('Coral Pukei-Pukei','Coral_Pukei-Pukei.png','3'),
('Deviljho','Deviljho.png','4'),
('Diablos','Diablos.png','3'),
('Dodogama','Dodogama.png','3'),
('Ebony Odogaron','Ebony_Odogaron.png','3'),
('Fatalis','Fatalis.png','6'),
('Frostfang Barioth','Frostfang_Barioth.png','3'),
('Fulfur Anjanath','Fulgur_Anjanath.png','3'),
('Furious Rajang','Furious_Rajang.webp','4'),
('Glavenus','Glavenus.png','3'),
('Gold Rathian','Gold_Rathian.png','3'),
('Great Girros','Great_Girros.png','3'),
('Great Jagras','Great_Jagras.png','3'),
('Jyuratodus','Jyuratodus.png','3'),
('Kirin','Kirin.png','4'),
('Kulu-Ya-Ku','Kulu-Ya-Ku.png','3'),
('Kulve Taroth','Kulve_Taroth.png','5'),
('Kushala Daora','Kushala_Daora.png','4'),
('Lavasioth','Lavasioth.png','3'),
('Legiana','Legiana.png','3'),
('Leshen','Leshen.png','3'),
('Lunastra','Lunastra.png','4'),
('Namielle','Namielle.png','4'),
('Nargacuga','Nargacuga.png','3'),
('Nergigante','Nergigante.png','4'),
('Nightshade Paolumu','Nightshade_Paolumu.png','3'),
('Odogaron','Odogaron.png','3'),
('Paolumu','Paolumu.png','3'),
('Pink Rathian','Pink_Rathian.png','3'),
('Pukei-Pukei','Pukei-Pukei.png','3'),
('Radobaan','Radobaan.png','3'),
('Raging Brachydios','Raging_Brachydios.png','4'),
('Rajang','Rajang.png','4'),
('Rathalos','Rathalos.png','3'),
('Rathian','Rathian.png','3'),
('Ruiner Nergigante','Ruiner_Nergigante.png','4'),
('Safi''Jiva','Safi''Jiva.png','6'),
('Savage Deviljho','Savage_Deviljho.png','4'),
('Scarred Yian Garuga','Scarred_Yian_Garuga.png','3'),
('Seething Bazelgeuse','Seething_Bazelgeuse.png','4'),
('Shara Ishvalda','Shara_Ishvalda.png','6'),
('Shrieking Legiana','Shrieking_Legiana.png','3'),
('Silver Rathalos','Silver_Rathalos.png','3'),
('Stygian Zinogre','Stygian_Zinogre.png','3'),
('Teostra','Teostra.png','4'),
('Tigrex','Tigrex.png','3'),
('Tobi-Kadachi','Tobi-Kadachi.png','3'),
('tzitzi-Ya-Ku','Tzitzi-Ya-Ku.png','3'),
('Uragaan','Uragaan.png','3'),
('Vaal Hazak','Vaal_Hazak.png','4'),
('Velkhana','Velkhana.png','4'),
('Viper Tobi-Kadachi','Viper_Tobi-Kadachi.png','3'),
('Xeno''jiva','Xeno''jiva.png','6'),
('Yian Garuga','Yian_Garuga.png','3'),
('Zinogre','Zinogre.png','3'),
('Zorah Magdaros','Zora:Magdaros.png','0');

insert into maps (MapName,MapIcon) values ('Dummie','Question_Mark.png','0'),('Acidic Glavenus','Acidic_Glavenus.png','3'),